### PR TITLE
fix: ForwardingLogger should foward block param

### LINKED ISSUE #1599: Log message passed in progname, not in message parameter
**Description of the bug**
When I am trying to run my app with a custom logger, the application fails to start with the following error:

```
myapp/lib/syslog/logger.rb:205:in `add': undefined method `call' for nil:NilClass (NoMethodError)

      @@syslog.log( (LEVEL_MAP[severity] | @facility), '%s', formatter.call(severity, Time.now, progname, (message || block.call)) )
                                                                                                                           ^^^^^
  from myapp/config/initializers/opentelemetry.rb:94:in `add'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-sdk-1.4.0/lib/opentelemetry/sdk/forwarding_logger.rb:49:in `info'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:79:in `install_instrumentation'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:51:in `block (2 levels) in install'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:46:in `each'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:46:in `block in install'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:45:in `synchronize'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-registry-0.3.0/lib/opentelemetry/instrumentation/registry.rb:45:in `install'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-sdk-1.4.0/lib/opentelemetry/sdk/configurator.rb:164:in `install_instrumentation'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-sdk-1.4.0/lib/opentelemetry/sdk/configurator.rb:145:in `configure'
  from myapp/shared/bundle/ruby/3.2.0/gems/opentelemetry-sdk-1.4.0/lib/opentelemetry/sdk.rb:66:in `configure'

```
I dug a little into it and can see that `ForwardingLogger` passes what should be a message into a `progname` parameter.
In [registry/lib/opentelemetry/instrumentation/registry.rb:81](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/registry/lib/opentelemetry/instrumentation/registry.rb#L81) we call `OpenTelemetry.logger.info 'Our message here'`
Then in [sdk/lib/opentelemetry/sdk/forwarding_logger.rb:48](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/forwarding_logger.rb#L48) we receive it as
`def info(progname = nil, &block)` thus we get our message in a `progname`.
Then it is passed to `def add(severity, message = nil, progname = nil)` in which signature me have message attribute, but when passing it, we [set it](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/forwarding_logger.rb#L49) to `nil`: `add(Logger::INFO, nil, progname, &block)`.
And then we omit the block and pass our `nil` message and a message in a `progname` to the originally selected `@logger`:
`@logger.add(severity, message, progname)`.

`ActiveSupport::Logger` does just fine, but my logger cannot bear both empty message and block, and I myself find it kind of weird: passing message in a progname.

Is it done supposedly for some reason or is it an error?

**Share details about your runtime**

Operating system details: Linux, Ubuntu 16.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.0"

### PR DESCRIPTION
**Pull request by BrianHawley**
Also added tests to verify the default forwarding logger level, and to make sure it actually forwards logs.

Fixes #1599

### CODE REVIEW

**Comment by arielvalentin** [comment]
@BrianHawley please review the EasyCLA.

If you accept it, we will proceed with a review of this PR.

Thank you.

**Comment by BrianHawley** [comment]
@arielvalentin license accepted, thanks.

**Review by arielvalentin — APPROVED** [review]

**Review by dazuma — APPROVED** [review]

**Comment by szechyjs** [comment]
This seems to also be busted when using `Ougai` as the logger.

**Comment by adamk9k** [comment]
This introduced a bug if the logger used is Semantic Logger

``` 
OpenTelemetry error: no block given (yield)
```

coming from https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/forwarding_logger.rb#L41

**Comment by kaylareopelle** [comment]
Thanks, @adamk9k! I'll open an issue for this to take a closer look. If you know what needs to be done to fix the problem, please feel free to open a PR.

**Comment by adamk9k** [comment]
> Thanks, @adamk9k! I'll open an issue for this to take a closer look. If you know what needs to be done to fix the problem, please feel free to open a PR.

Thank you @kaylareopelle in the meantime I've figured out what the issue was. It was coming from `common/lib/opentelemetry/common/utilities.rb` version 0.20.0 when it looked like this

```ruby
def untraced
  Context.with_value(UNTRACED_KEY, true) do |ctx, _|
    yield ctx
  end
end
```

upgrading to 0.21.0 that includes this https://github.com/open-telemetry/opentelemetry-ruby/pull/1634 fixed it.

**Comment by kaylareopelle** [comment]
@adamk9k, that's great news! It sounds like nothing further needs to be done, and https://github.com/open-telemetry/opentelemetry-ruby/issues/1738 can be closed. Is that correct?

**Comment by adamk9k** [comment]
@kaylareopelle yes, thank you and sorry for the noise.

**Comment by kaylareopelle** [comment]
@adamk9k, no problem! Thanks for the update!

**Pull request merged**
