### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BobinMathew**
issue #753

Note:
 Some edits are required in the last few paragraphs

### CODE REVIEW

**Comment by robertlaurin** [comment]
Hey @BobinMathew could you follow the comment made by @arielvalentin?  -> https://github.com/open-telemetry/opentelemetry-ruby/issues/753#issuecomment-842502725

The java implementation took the approach suggested above as well https://github.com/open-telemetry/opentelemetry-java/blob/main/code-of-conduct.md

This way we don't have to worry about our copy falling out of sync if the community code of conduct changes at any point.

**Comment by BobinMathew** [comment]
Hi @robertlaurin, is this what you want ?

**Comment by fbogsany** [comment]
@BobinMathew can you please [sign the CLA](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/189070633/756/#/?version=1)?

**Comment by BobinMathew** [comment]
> @BobinMathew can you please [sign the CLA](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/189070633/756/#/?version=1)?

I did ;but it's not working.
I signed a CLA with opentelemetry-cpp, it worked.
Now when I sign its redirecting to the opentelemetry-cpp repo

**Comment by fbogsany** [comment]
Hmm, weird - can you try pushing an empty commit?

**Comment by BobinMathew** [comment]
I think the problem's solved now 😃

**Pull request merged**
