### PR TITLE
Fix link to library config

### PR DESCRIPTION
**Pull request by cartermp**
This fix ensures we can update the docs on the website. `relref` links are necessary for most links, which I missed in my first pass here!

### CODE REVIEW

**Review by arielvalentin — APPROVED** [review]

**Review by ericmustin — APPROVED** [review]

**Review by chalin — CHANGES_REQUESTED** [review]
Rather than:

```markdown
[configure-specific-libraries]({{< relref "configuring_automatic_instrumentation#configuring-specific-instrumentation-libraries" >}})
```

I think that you meant to write:

```markdown
[configure-specific-libraries]: {{< relref "configuring_automatic_instrumentation#configuring-specific-instrumentation-libraries" >}}
```

**Review by arielvalentin — APPROVED** [review]

**Comment by chalin** [comment]
(I'd have made the edit myself, but don't have the permissions.)

**Comment by arielvalentin** [comment]
Thanks @chalin! 

@cartermp would you kindly apply their suggestion?

**Comment by cartermp** [comment]
Weird, what I had allowed me to build the site locally - but this is more uniform w.r.t the other links

**Review by chalin — APPROVED** [review]
LGTM

**Comment by chalin** [comment]
Hi all: can we get this merged soon?

**Review by mwear — APPROVED** [review]
LGTM

**Pull request merged**
