### PR TITLE
fix: Release config for test helpers

### PR DESCRIPTION
**Pull request by arielvalentin**

### CODE REVIEW

**Comment by plantfansam** [comment]
Original PR that added the gem: https://github.com/open-telemetry/opentelemetry-ruby/pull/1170/files?

**Comment by plantfansam** [comment]
Original PR that added the gem: https://github.com/open-telemetry/opentelemetry-ruby/pull/1170/files?

**Review by plantfansam — APPROVED** [review]

**Comment by arielvalentin** [comment]
> Original PR that added the gem: https://github.com/open-telemetry/opentelemetry-ruby/pull/1170/files?

Yes looks right to me

**Review by fbogsany — APPROVED** [review]

**Comment by arielvalentin** [comment]
@open-telemetry/ruby-maintainers 👋🏼 I would like to release this if someone could merge this 🙏🏼

**Review by mwear — APPROVED** [review]

**Pull request merged**
