### PR TITLE
Add README for Ethon

### PR DESCRIPTION
**Pull request by xukaren**
This PR adds documentation for OpenTelemetry's Ethon Instrumentation, closing open-telemetry#235.

The README follows the examples for instrumentation/ethon/README.md and instrumentation/sidekiq/README.md.

### CODE REVIEW

**Review by mwear — COMMENTED** [review]
👋 Welcome and thanks for the contribution! This looks good, but I think it'd be an improvement if we point out that there is an example in the examples directory. WDYT?

**Comment by xukaren** [comment]
That's a great idea! I've added an examples section in the new commit. Is this what you were looking for?

**Review by fbogsany — APPROVED** [review]
Thanks @xukaren!

**Review by robertlaurin — APPROVED** [review]

**Comment by fbogsany** [comment]
@xukaren this looks great! I can merge after a rebase.

**Review by mwear — APPROVED** [review]

**Comment by mwear** [comment]
Thanks @xukaren!

**Pull request merged**
