### PR TITLE
Removing binary format

### PR DESCRIPTION
**Pull request by minond**
Resolves https://github.com/open-telemetry/opentelemetry-ruby/issues/194

### CODE REVIEW

**Comment by minond** [comment]
I signed the CLA before creating this PR, so I'm not sure why that step is failing. I'm double checking I did everything right.

**Comment by mwear** [comment]
:wave: welcome @minond! If you're still having issues with signing the CLA, you can take a look at the FAQ here: https://identity.linuxfoundation.org/projects/cncf.

**Comment by minond** [comment]
I signed it

**Comment by minond** [comment]
*cough* *cough*  ok... I guess the third time's the charm. @mwear, this is ready for review when you are.

**Pull request merged**
