### PR TITLE
chore: Fix typos in code comments in the Mysql2 instrumentation

### PR DESCRIPTION
**Pull request by johnnyshields**

### CODE REVIEW

**Review by fbogsany — APPROVED** [review]

**Comment by fbogsany** [comment]
I've approved this, however you'll need to sign the CLA @johnnyshields before I can merge it.

**Review by robertlaurin — APPROVED** [review]

**Review by ericmustin — APPROVED** [review]
ty for the cleanup here, lgtm. I do not like this butterfly keyboard one bit 😅

**Comment by johnnyshields** [comment]
Can someone merge this? I'm fighting the CI on this project it looks like.

**Comment by dazuma** [comment]
@johnnyshields We can't merge it until you sign the CLA.

**Comment by dazuma** [comment]
@johnnyshields Do you see the link in the first comment from communitybridge-easycla? We need contributors to sign the contributor licensing agreement, to make sure that we have your permission to include your code contribution under the project's license.

**Comment by johnnyshields** [comment]
I've signed the CLA, but EasyCLA check still not passing. How long do I have to wait after signing?

**Comment by dazuma** [comment]
It's supposed to take effect quickly. Did you use the same email address listed in your git commit? (i.e. your `user.email` git config?)

**Comment by johnnyshields** [comment]
Yes, I did.

By the way, the link in the first comment links to a broken page... I referred to the project readme to find a different link.

image

**Comment by johnnyshields** [comment]
I've submitted a JIRA to get assistance. Will see what they say.

**Comment by dazuma** [comment]
Hmm. I also think the EasyCLA app integration is set up at the org level. @mwear Do you have org permissions (or know someone who does) and can check on whether we're set up correctly (and maybe whether johnnyshields's sign-up has taken effect properly?)

**Comment by johnnyshields** [comment]
I did add the "EasyCLA" app plugin to my Github and selected all repos.

**Comment by johnnyshields** [comment]
OK, got my CLA fixed after much wrangling. Had to push this as a new commit. Please approve.

**Pull request merged**
