### PR TITLE
fix: Update SDK BaggageManager to match API

### PR DESCRIPTION
**Pull request by arielvalentin**
The API defines a `build` helper method that was named `build_context` in the SDK implementation.

This change renames the SDK to make it consistent with the API.

### CODE REVIEW

**Review by fbogsany — APPROVED** [review]

**Review by mwear — APPROVED** [review]

**Comment by fbogsany** [comment]
I can merge this after a rebase (strangely, I don't have that option in the GitHub UI).

**Comment by arielvalentin** [comment]
That is strange. What are the branch protection rules?

**Comment by fbogsany** [comment]
> ~That is strange. What are the branch protection rules?~ are you trying to rebase it on our forked repo?

Yep - the button is available for most people's PRs (from their forked repos), but for a few, like yours, it isn't shown.

**Comment by arielvalentin** [comment]
@fbogsany I have not looked into this but it is likely because we created this fork on our organization account.

**Pull request merged**
