### PR TITLE
fix: index a link trace_id in middle rather than end

### PR DESCRIPTION
**Pull request by chrisholmes**
A link's trace_id was being indexed at the end of the string rather than the
middle which was causing it to return nil and the exporter to throw an
undefined method exception when trying to convert nil into a int64:

```
undefined method '<' for nil:NilClass
```

### CODE REVIEW

**Comment by fbogsany** [comment]
Thanks for catching this. Can you please add (to) a test that covers this? Also, can you please sign the CLA?

**Comment by chrisholmes** [comment]
> Thanks for catching this. Can you please add (to) a test that covers this? Also, can you please sign the CLA?

Sure, a test has been included.

I'm working on the CLA within my organisation now.

**Comment by chrisholmes** [comment]
@fbogsany the CLA is now sorted :)

**Review by fbogsany — APPROVED** [review]

**Comment by fbogsany** [comment]
@chrisholmes can you please rebase? This is next in the queue to merge.

**Review by robertlaurin — APPROVED** [review]

**Comment by chrisholmes** [comment]
@fbogsany should be sorted now

**Pull request merged**
