### PR TITLE
fix: untraced only works with parent-based sampler

### PR DESCRIPTION
**Pull request by fbogsany**
The `untraced` helper currently only works when a parent-based sampler is installed. As an example, it will not suppress spans if the `ALWAYS_ON` sampler is installed.

This fixes `untraced` to work regardless of the sampler. It does this by communicating via a private `Context` key. An additional helper `untraced?` is introduced to query the state of the key from the `Context`. The SDK `Tracer#start_span` implementation is updated to check for `untraced?` before delegating either to the API `Tracer#start_span` method or to `TracerProvider#internal_start_span`.

The OpenTelemetry JS implementation offers the same functionality implemented in the same way, and serves as inspiration for the implementation in this PR.

### CODE REVIEW

**Review by arielvalentin — APPROVED** [review]
Assuming linter errors are addressed.

**Comment by fbogsany** [comment]
> Assuming linter errors are addressed.

I blame Copilot.

**Comment by fbogsany** [comment]
We'll have to be careful with the version bumps when releasing this. We've added a method to the `-common` gem that the `-sdk` now depends on, but we haven't changed the `-sdk` interface.

**Comment by fbogsany** [comment]
> Shouldn't we add a dependency on `-common` to the sdk gemspec?

It's already there.

**Comment by ahayworth** [comment]
> > Shouldn't we add a dependency on -common to the sdk gemspec?
> It's already there.

🤦 Wow - it is indeed, I must have skipped over it when I was hunting for it. 🤦

**Review by ahayworth — APPROVED** [review]

**Review by arielvalentin — APPROVED** [review]

**Review by robertlaurin — APPROVED** [review]

**Review by robbkidd — APPROVED** [review]

**Pull request merged**
