### PR TITLE
"all" gem is missing ruby_kafka

### PR DESCRIPTION
**Pull request by johnnyshields**
It would be nice if the release process could automatically update the `all` instrumentation gem so that this is not missed in the future.

Please cut a release (0.12.1?) after merging.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@fbogsany please merge.

**Review by robertlaurin — APPROVED** [review]
>It would be nice if the release process could automatically update the all instrumentation gem so that this is not missed in the future.

Yeah I agree, I added an instrumentation boilerplate generator that automatically adds to the `all` gem to alleviate this, but the ruby kafka pr predated it.

**Review by fbogsany — CHANGES_REQUESTED** [review]
This also needs `require 'opentelemetry-instrumentation-ruby_kafka'` in `instrumentation/all/lib/opentelemetry/instrumentation/all.rb`

**Comment by johnnyshields** [comment]
@fbogsany done

**Review by mwear — APPROVED** [review]

**Review by fbogsany — APPROVED** [review]

**Pull request merged**
