### PR TITLE
Fix: XRay propagator null exception

### PR DESCRIPTION
**Pull request by scar-lovevery**
This is in reference to: 
https://github.com/open-telemetry/opentelemetry-ruby/issues/832

### CODE REVIEW

**Review by ahayworth — APPROVED** [review]
LGTM - is it possible to add a quick test case for this too?

**Comment by scar-lovevery** [comment]
Added a test.

**Review by robertlaurin — APPROVED** [review]
This looks good to me, you will need to sign the CLA before I can merge it in though.

**Comment by scar-lovevery** [comment]
Done.

**Review by fbogsany — APPROVED** [review]

**Pull request merged**
