### PR TITLE
Fix constant reference in ConsistentProbabilityTraceState

### PR DESCRIPTION
**Pull request by plantfansam**
`.DEFAULT` -> `::DEFAULT`

### CODE REVIEW

**Comment by plantfansam** [comment]
Specs are failing for unrelated reason:

> In Gemfile:
  rubocop was resolved to 0.73.0, which depends on
    jaro_winkler

I think potentially [jaro_winkler](https://github.com/tonytonyjan/jaro_winkler/) hasn't released the JRuby-compatible version of 1.5.5):

image

rubocop no longer depends on jaro-winkler so we can potentially just upgrade rubocop, but that's actually some work #1321.

**Comment by ericmustin** [comment]
I think it's fine to merge , can ignore test suite imo? Wdyt?

**Comment by plantfansam** [comment]
> I think it's fine to merge , can ignore test suite imo? Wdyt?

test passage is not a blocker for me, but i am working on fixing specs

**Comment by plantfansam** [comment]
Working on rubocop upgrades here https://github.com/open-telemetry/opentelemetry-ruby/pull/1452

**Review by fbogsany — APPROVED** [review]

**Pull request merged**
