### PR TITLE
docs: describe Tracer#in_span arguments

### PR DESCRIPTION
**Pull request by kaylareopelle**
These parameter descriptions are based on comments in the [`OpenTelemetry::SDK::Trace::SpanData` Struct](https://github.com/kaylareopelle/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/span_data.rb#L13-L30).

I came across this when I recently needed to add `:kind` to a `Tracer#in_span` call and the [current RubyDoc](https://rubydoc.info/gems/opentelemetry-api/OpenTelemetry/Trace/Tracer#in_span-instance_method) didn't describe how to do so.

### CODE REVIEW

**Review by arielvalentin — APPROVED** [review]

**Review by robbkidd — APPROVED** [review]
Yessss, more better docs!

**Comment by kaylareopelle** [comment]
It looks like Rubocop is upset about `./` included in the file arguments for `require_relative` in the Semantic Conventions code. I made a new PR to address those: https://github.com/open-telemetry/opentelemetry-ruby/pull/1475 

The other error is related to TruffleRuby and seems to also happen for the Metrics WIP PRs. Would you like me to make a bug report for this issue?

**Comment by robertlaurin** [comment]
>The other error is related to TruffleRuby and seems to also happen for the Metrics WIP PRs. Would you like me to make a bug report for this issue?

That would be appreciated!

**Comment by kaylareopelle** [comment]
> > The other error is related to TruffleRuby and seems to also happen for the Metrics WIP PRs. Would you like me to make a bug report for this issue?
> 
> That would be appreciated!

Great! Here's the bug report: https://github.com/open-telemetry/opentelemetry-ruby/issues/1476

**Pull request merged**
